### PR TITLE
allow sass binary path to passed

### PR DESCRIPTION
**Pull request by nick-less**

### CODE REVIEW

**Comment by sindresorhus** [comment]
No thanks. Just add it to your $PATH. That way it will work for any other tool using it too.

**Comment by nick-less** [comment]
hm, we have setups where using the path is not possible (e.g frontend builds using maven-frontend-plugin, where build dependencies (node, grunt, sass..) are installed on the fly). 
No chance to add these three lines?

**Comment by sindresorhus** [comment]
There's always a way. You could also just modify `process.env.PATH` in the gruntfile.

It's never "just adding 3 lines". It requires docs, tests, and creates overhead for the user that has to understand it.

**Comment by nick-less** [comment]
Ok modifing  process.env.PATH would allow me to add the path, but it wont allow me to invoke "node-sass" instead of "sass"...

**Comment by sindresorhus** [comment]
`node-sass` is not compatible anyways. Use https://github.com/sindresorhus/grunt-sass if you want `node-sass`.

**Pull request closed without merging**
